[phases.setup]
nixPkgs = ["...", "python310"]

[phases.build]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[healthcheck]
path = "/health"
timeout = 100
